import {
  Apple,
  BadgeCheck,
  Banknote,
  CircleHelp,
  CloudSun,
  Coins,
  CreditCard,
  Droplets,
  FileCheck,
  FlaskConical,
  HandCoins,
  HandHelping,
  HeartPulse,
  Home,
  LayoutGrid,
  Leaf,
  Megaphone,
  MessageSquare,
  Mountain,
  PiggyBank,
  ShieldCheck,
  Store,
  Tractor,
  Trees,
  UserPlus,
  Users,
  Warehouse,
  Waves,
  Wheat,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  apple: Apple,
  "badge-check": BadgeCheck,
  banknote: Banknote,
  "cloud-sun": CloudSun,
  coins: Coins,
  "credit-card": CreditCard,
  droplets: Droplets,
  "file-check": FileCheck,
  "flask-conical": FlaskConical,
  "hand-coins": HandCoins,
  "hand-helping": HandHelping,
  "heart-pulse": HeartPulse,
  home: Home,
  "layout-grid": LayoutGrid,
  leaf: Leaf,
  megaphone: Megaphone,
  "message-square": MessageSquare,
  mountain: Mountain,
  "piggy-bank": PiggyBank,
  "shield-check": ShieldCheck,
  store: Store,
  tractor: Tractor,
  trees: Trees,
  "user-plus": UserPlus,
  users: Users,
  warehouse: Warehouse,
  waves: Waves,
  wheat: Wheat,
};

/** Resolves a JSON icon key to a lucide component, with a safe fallback. */
export function getIcon(key: string): LucideIcon {
  return ICONS[key] ?? CircleHelp;
}
